version: "3.8"

services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - khunlook

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: on-failure:10
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: development
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
    networks:
      - khunlook

networks:
  khunlook:
    driver: bridge
