version: "3.8"

services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: APPDEK032022
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - khunlook

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: development
      MYSQL_HOST: mysql
      MYSQL_DATABASE: APPDEK032022
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    networks:
      - khunlook
    depends_on:
      - mysql
    restart: on-failure:10

networks:
  khunlook:
    external: true
