name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | sudo docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Pull latest Docker image
        run: sudo docker pull d33102/khunlook:latest

      - name: Stop and remove old Docker container (if exists)
        run: |
          sudo docker stop khunlook-container || true
          sudo docker rm khunlook-container || true

      - name: Run new Docker container
        run: sudo docker run -d -p 8080:8080 --name khunlook-container d33102/khunlook:latest
