name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Pull latest Docker images
        run: sudo docker-compose pull

      - name: Stop and remove old containers
        run: sudo docker-compose down -v

      - name: Start new containers
        run: sudo docker-compose up -d --build

      - name: MySQL Remote Access
        run: |
          sleep 10
          sudo docker exec mysql mysql -u root -p${{ secrets.SQL_PASSWORD }} -e "
          ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '${{ secrets.SQL_PASSWORD }}';
          GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
          FLUSH PRIVILEGES;"
